document.getElementById('exportBtn').addEventListener('click', async () => {
  const btn = document.getElementById('exportBtn');
  const status = document.getElementById('status');

  btn.disabled = true;
  btn.textContent = 'Exporting...';
  status.textContent = '';

  try {
    const cookies = await chrome.cookies.getAll({ domain: '.youtube.com' });

    if (cookies.length === 0) {
      status.textContent = 'No YouTube cookies found. Are you logged in?';
      btn.disabled = false;
      btn.textContent = 'Export Cookies.txt';
      return;
    }

    let cookieText = '# Netscape HTTP Cookie File\n';
    cookieText += '# This file was generated by YouTube Cookie Exporter\n\n';

    const now = Math.floor(Date.now() / 1000);

    for (const cookie of cookies) {
      const expires = cookie.expirationDate ? Math.floor(cookie.expirationDate) : now + 86400 * 30;
      const domain = cookie.domain.startsWith('.') ? cookie.domain : '.' + cookie.domain;
      const secure = cookie.secure ? 'TRUE' : 'FALSE';
      const path = cookie.path || '/';

      cookieText += `${domain}\t${secure}\t${path}\t${cookie.session ? 'FALSE' : 'TRUE'}\t${expires}\t${cookie.name}\t${cookie.value}\n`;
    }

    const blob = new Blob([cookieText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);

    await chrome.downloads.download({
      url: url,
      filename: 'youtube_cookies.txt',
      saveAs: true
    });

    status.textContent = `Exported ${cookies.length} cookies`;
    btn.textContent = 'Export Cookies.txt';
    btn.disabled = false;

  } catch (err) {
    status.textContent = 'Error: ' + err.message;
    btn.disabled = false;
    btn.textContent = 'Export Cookies.txt';
  }
});