const FALLBACK_TTL_SECONDS = 86400 * 30;

// Prefer the incognito cookie store when a private window is open: exporting
// from a throwaway session that gets closed right after is what keeps YouTube
// from rotating (and effectively expiring) the cookies.
async function pickCookieStore() {
  const stores = await chrome.cookies.getAllCookieStores();
  const incognito = stores.find((store) => store.id !== '0');
  if (incognito) {
    return { storeId: incognito.id, incognito: true };
  }
  return { storeId: stores[0] ? stores[0].id : undefined, incognito: false };
}

function toNetscape(cookies) {
  // Netscape field order: domain, include-subdomains flag, path, secure,
  // expiry, name, value. yt-dlp rejects or misapplies cookies when the flag
  // and secure columns are swapped.
  let text = '# Netscape HTTP Cookie File\n';
  text += '# This file was generated by YouTube Cookie Exporter\n\n';

  const now = Math.floor(Date.now() / 1000);

  for (const cookie of cookies) {
    const domain = cookie.domain.startsWith('.') ? cookie.domain : '.' + cookie.domain;
    const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const path = cookie.path || '/';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expires = cookie.expirationDate ? Math.floor(cookie.expirationDate) : now + FALLBACK_TTL_SECONDS;

    text += `${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expires}\t${cookie.name}\t${cookie.value}\n`;
  }

  return text;
}

document.getElementById('exportBtn').addEventListener('click', async () => {
  const btn = document.getElementById('exportBtn');
  const status = document.getElementById('status');
  const hint = document.getElementById('hint');

  btn.disabled = true;
  btn.textContent = 'Exporting...';
  status.textContent = '';
  hint.textContent = '';

  try {
    const { storeId, incognito } = await pickCookieStore();
    const cookies = await chrome.cookies.getAll({ domain: '.youtube.com', storeId });

    if (cookies.length === 0) {
      status.textContent = incognito
        ? 'No YouTube cookies in the incognito window. Did you log in there?'
        : 'No YouTube cookies found. Are you logged in?';
      btn.disabled = false;
      btn.textContent = 'Export Cookies.txt';
      return;
    }

    const blob = new Blob([toNetscape(cookies)], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);

    await chrome.downloads.download({
      url: url,
      filename: 'youtube_cookies.txt',
      saveAs: true
    });
    URL.revokeObjectURL(url);

    status.textContent = incognito
      ? `Exported ${cookies.length} cookies from the incognito window. Close it now and don't reuse that login.`
      : `Exported ${cookies.length} cookies from your normal profile.`;

    if (!incognito) {
      const allowed = await chrome.extension.isAllowedIncognitoAccess();
      hint.textContent = allowed
        ? 'Tip: log in with a spare account in an incognito window and export from there so the cookies stop expiring.'
        : 'Tip: enable "Allow in Incognito" for this extension (chrome://extensions) to export longer-lasting cookies from a private window.';
    }

    btn.textContent = 'Export Cookies.txt';
    btn.disabled = false;

  } catch (err) {
    status.textContent = 'Error: ' + err.message;
    btn.disabled = false;
    btn.textContent = 'Export Cookies.txt';
  }
});
